name: advent_of_code_2024
description: Solutions for Advent of Code 2024.
version: 1.0.0
repository: https://github.com/mateusfccp/advent_of_code_2024

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.19.1
  meta: ^1.16.0
  petitparser: 6.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
